// LICENSE_CODE ZON
'use strict'; /*jshint browser:true*/
define(function(){
return 'google.com facebook.com youtube.com yahoo.com baidu.com qq.com '
+'live.com linkedin.com weibo.com yandex.ru sohu.com soso.com pinterest.com '
+'tumblr.com msn.com instagram.com apple.com xvideos.com ifeng.com imdb.com '
+'xhamster.com bbc.co.uk stackoverflow.com people.com.cn imgur.com '
+'alibaba.com akamaihd.net alipay.com cnn.com vube.com huffingtonpost.com '
+'reddit.com wordpress.org odnoklassniki.ru xinhuanet.com conduit.com '
+'flickr.com t.co gmw.cn espn.go.com pornhub.com youku.com ku6.com '
+'blogspot.in about.com bp.blogspot.com rakuten.co.jp netflix.com '
+'dailymotion.com adcash.com cnet.com dailymail.co.uk kickass.to vimeo.com '
+'indiatimes.com xnxx.com redtube.com walmart.com youporn.com uol.com.br '
+'aol.com sogou.com livejasmin.com weather.com themeforest.net nytimes.com '
+'amazonaws.com adf.ly dropbox.com directrev.com pixnet.net slideshare.net '
+'mozilla.org globo.com etsy.com wikimedia.org deviantart.com ameblo.jp '
+'fiverr.com wikia.com blogfa.com thepiratebay.sx hootsuite.com outbrain.com '
+'livejournal.com yelp.com livedoor.com bestbuy.com badoo.com 4shared.com '
+'buzzfeed.com mediafire.com flipkart.com media.tumblr.com torrentz.eu '
+'theguardian.com bankofamerica.com china.com.cn stumbleupon.com google.co.ve '
+'foxnews.com forbes.com aweber.com addthis.com chase.com sourceforge.net '
+'files.wordpress.com skype.com naver.com espncricinfo.com soundcloud.com '
+'archive.org allegro.pl tube8.com answers.com spiegel.de github.com '
+'mailchimp.com indeed.com usps.com nicovideo.jp bet365.com warriorforum.com '
+'it168.com reference.com onet.pl wellsfargo.com photobucket.com jd.com '
+'mashable.com gameforge.com gamer.com.tw fedex.com bild.de '
+'thefreedictionary.com pandora.com zedo.com stackexchange.com goo.ne.jp '
+'taringa.net tianya.cn popads.net so.com wordreference.com naver.jp '
+'delta-search.com google.dz pcpop.com telegraph.co.uk yesky.com in.com '
+'gmx.net tripadvisor.com weebly.com nbcnews.com samsung.com clkmon.com '
+'nfl.com rediff.com leboncoin.fr rambler.ru goodreads.com ettoday.net '
+'uploaded.net rutracker.org comcast.net ucoz.ru hurriyet.com.tr wsj.com '
+'time.com wix.com ikea.com kaskus.co.id zillow.com wp.pl upworthy.com '
+'avito.ru domaintools.com sharelive.net cnzz.com usatoday.com huanqiu.com '
+'dmm.co.jp loading-delivery1.com moz.com jobfindgold.info m2newmedia.com '
+'baomihua.com bleacherreport.com mywebsearch.com free.fr web.de tmz.com '
+'goal.com businessinsider.com ndtv.com hulu.com milliyet.com.tr youdao.com '
+'bitly.com chinaz.com codecanyon.net ehow.com disqus.com enet.com.cn '
+'9gag.com scribd.com olx.in qtrax.com chaturbate.com constantcontact.com '
+'libero.it orange.fr mercadolivre.com.br mobile01.com varzesh3.com nba.com '
+'washingtonpost.com detik.com retailmenot.com twitch.tv extratorrent.cc '
+'xing.com hudong.com xywy.com beeg.com quikr.com tagged.com dell.com '
+'ero-advertising.com cj.com hardsextube.com kohls.com thefreecamsecret.com '
+'snapdeal.com v1.cn newegg.com youjizz.com putlocker.com histats.com '
+'onclickads.net reuters.com motherless.com macys.com qvo6.com ign.com 39.net '
+'kooora.com bitauto.com infusionsoft.com clickbank.com nih.gov snapdo.com '
+'repubblica.it gsmarena.com feedly.com jabong.com hdfcbank.com bloomberg.com '
+'kakaku.com bluehost.com 4dsply.com pof.com xe.com intoday.in webmd.com '
+'siteadvisor.com zippyshare.com caijing.com.cn doublepimp.com yandex.ua '
+'cntv.cn ebay.in doubleclick.com rt.com pchome.net twoo.com '
+'empowernetwork.com tinyurl.com elpais.com microsoftonline.com ig.com.br '
+'seznam.cz daum.net speedtest.net rayli.com.cn w3.org eazel.com marca.com '
+'blogspot.de accuweather.com imageshack.us coccoc.com steampowered.com '
+'list-manage.com odesk.com uimserv.net nydailynews.com elmundo.es '
+'capitalone.com 123rf.com drudgereport.com goodgamestudios.com '
+'cloudfront.net naukri.com ck101.com force.com ameba.jp ad6media.fr aili.com '
+'t-online.de habrahabr.ru optmd.com douban.com homedepot.com meetup.com '
+'etao.com jrj.com.cn chip.de webmoney.ru myntra.com adultfriendfinder.com '
+'justdial.com xyxy.net swagbucks.com gazeta.pl okcupid.com getresponse.com '
+'fbcdn.net icicibank.com doorblog.jp jimdo.com quora.com blackhatworld.com '
+'slickdeals.net digg.com hypergames.net latimes.com myfreecams.com '
+'corriere.it commentcamarche.net webs.com mercadolibre.com.ar issuu.com '
+'match.com toysrus.com techcrunch.com informer.com thepiratebay.se '
+'lady8844.com vnexpress.net typepad.com sberbank.ru eyny.com '
+'australianbrewingcompany.com livescore.com java.com bbc.com shareasale.com '
+'zing.vn xgo.com.cn clixsense.com exoclick.com probux.com thepiratebay.pe '
+'irctc.co.in viralnova.com rapidgator.net pixiv.net gutefrage.net '
+'babytree.com abcnews.go.com sahibinden.com linkbucks.com backpage.com '
+'yaolan.com xda-developers.com lenta.ru elance.com youm7.com fotolia.com '
+'ce.cn iqiyi.com cbssports.com subscene.com lefigaro.fr lemonde.fr narod.ru '
+'liveleak.com hatena.ne.jp lifehacker.com drtuber.com oneindia.in 55bbs.com '
+'rbc.ru bhaskar.com kijiji.ca kickstarter.com haber7.com kinopoisk.ru '
+'shaadi.com engadget.com seesaa.net examiner.com twimg.com mihanblog.com '
+'tudou.com eonline.com mp3skull.com tabelog.com gizmodo.com vitaminl.tv '
+'mama.cn cy-pr.com movie4k.to timeanddate.com free-tv-video-online.me '
+'farsnews.com theblaze.com marketwatch.com xbox.com haberturk.com mynet.com '
+'yellowpages.com scoop.it turbobit.net persianblog.ir rednet.cn '
+'all-free-download.com pr-cy.ru cbslocal.com staples.com clarin.com ca.gov '
+'soku.com urbandictionary.com jqw.com softpedia.com jquery.com facenama.com '
+'foxsports.com mercadolibre.com.ve chexun.com custhelp.com agoda.com '
+'zimbio.com majesticseo.com dreamstime.com costco.com templatemonster.com '
+'cnbc.com likes.com mobile.de barnesandnoble.com cracked.com dict.cc '
+'gamefaqs.com houzz.com slate.com tabnak.ir hidemyass.com mackolik.com '
+'leo.org azlyrics.com premierleague.com sakura.ne.jp gawker.com ovh.net '
+'howstuffworks.com lipixeltrack.com zanox.com monster.com news.com.au '
+'pixlr.com vk.me 2345.com pcbaby.com.cn focus.de npr.org cam4.com '
+'mirror.co.uk fhserve.com wired.com flipora.com squidoo.com lanacion.com.ar '
+'viadeo.com europa.eu allocine.fr b5m.com jeuxvideo.com sulekha.com '
+'xtube.com nifty.com indianrail.gov.in tutsplus.com 6.cn '
+'greatappsdownload.com today.com traidnt.net rottentomatoes.com eastday.com '
+'spankwire.com nhl.com klikbca.com independent.co.uk duckduckgo.com '
+'dosearches.com pcmag.com r10.net jobrapido.com lequipe.fr anonym.to '
+'24h.com.vn xunlei.com hespress.com deezer.com interia.pl trklnks.com '
+'letitbit.net renren.com bankmellat.ir people.com sahadan.com m-w.com '
+'americanas.com.br ancestry.com espnfc.com jvzoo.com worldstarhiphop.com '
+'wetransfer.com whitepages.com mega.co.nz heise.de life.com.tw zazzle.com '
+'hotels.com chron.com playstation.com thechive.com prothom-alo.com lowes.com '
+'voc.com.cn airtel.in sex.com weheartit.com addmefast.com stockstar.com '
+'bravotube.net dhl.de linkwithin.com linternaute.com gateable.com '
+'ellechina.com theverge.com gogetlinks.net youtube-mp3.org cdiscount.com '
+'ensonhaber.com shutterfly.com keezmovies.com 126.com avast.com '
+'shopclues.com jcpenney.com sapo.pt payoneer.com nokia.com nerdbux.com '
+'babycenter.com 17ok.com nownews.com battlefield.com fatakat.com '
+'adrotator.se ibm.com dhgate.com idnes.cz hm.com keepvid.com idealo.de '
+'yandex.kz sfr.fr digikala.com ezinearticles.com biblegateway.com '
+'biglobe.ne.jp leagueoflegends.com tigerdirect.com india.com ctrip.com '
+'nikkei.com reverso.net ixxx.com prestashop.com glassdoor.com subito.it '
+'welt.de nuvid.com 4399.com streamcloud.eu dx.com dafont.com '
+'largeporntube.com bannersdontwork.com southwest.com bestblackhatforum.com '
+'usmagazine.com chinabyte.com dmoz.org ria.ru rutor.org imagebam.com '
+'magentocommerce.com hongkiat.com as.com fifa.com pornhublive.com zoho.com '
+'walgreens.com change.org buscape.com.br yoka.com fnac.com xhamstercams.com '
+'yify-torrents.com mpnrs.com gulfup.com woot.com nypost.com priceline.com '
+'pinshan.com immobilienscout24.de myegy.com nike.com feedburner.com '
+'primewire.ag screencast.com maktoob.com gittigidiyor.com verizon.com '
+'wenku.baidu.com sfgate.com 51fanli.com kayak.com adscale.de ovh.com '
+'rakuten.ne.jp fool.com myspace.com woorank.com smh.com.au asus.com '
+'yourlust.com ahrefs.com ashleyrnadison.com milanuncios.com anysex.com '
+'weather.gov clicksor.com wmmail.ru gismeteo.ru digitalpoint.com '
+'privatehomeclips.com kdnet.net onlylady.com novinky.cz dealfish.co.th '
+'cheezburger.com banglanews24.com pagesjaunes.fr hi5.com makemytrip.com '
+'lapatilla.com webhostingtalk.com shopify.com kompas.com prntscr.com '
+'video-one.com aparat.com porn.com icicibank.co.in ucoz.com gstatic.com '
+'pantip.com sitepoint.com basecamp.com gtmetrix.com internethaber.com '
+'inbox.com aftonbladet.se way2sms.com exblog.jp oyunskor.com yomiuri.co.jp '
+'viva.co.id qone8.com brainyquote.com grooveshark.com miniclip.com '
+'ad4game.com realtor.com nationalgeographic.com solarmovie.so dantri.com.vn '
+'manta.com viooz.co pornmd.com vice.com kmart.com dubizzle.com sky.com '
+'box.com namecheap.com graphicriver.net watchseries.lt kioskea.net '
+'victoriassecret.com infobae.com shopathome.com instructables.com '
+'businessweek.com mayoclinic.com lacaixa.es csdn.net wmtransfer.com '
+'forobeta.com careerbuilder.com ozon.ru mixi.jp firstpost.com '
+'searchenginewatch.com friv.com spotify.com japanpost.jp cbs.com mediaset.it '
+'leadpages.net united.com nairaland.com peyvandha.ir dmm.com excite.co.jp '
+'chinatimes.com cnmo.com elegantthemes.com gamestop.com acesse.com '
+'picmonkey.com wiocha.pl pchome.com.tw mgid.com billdesk.com ppstream.com '
+'correios.com.br squarespace.com livedoor.biz 6pm.com bloglovin.com '
+'mapquest.com disney.go.com bitshare.com cbc.ca tinypic.com seekingalpha.com '
+'sueddeutsche.de nu.nl eluniversal.com.mx comcast.com sporx.com 1und1.de '
+'gazzetta.it zara.com windowsphone.com gamespot.com ticketmaster.com '
+'earthlink.net makeuseof.com bahn.de indiamart.com eventbrite.com '
+'searchnu.com icloud.com thehindu.com freepik.com mangareader.net orf.at '
+'porntube.com pingdom.com woothemes.com 4chan.org nowvideo.sx'.split(' ');
});
